[project]
name = "allgorythms"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "black>=25.1.0",
    "requests>=2.32.5",
    "scikit-learn>=1.7.1",
    "torch>2.1.0",
]

[tool.black]
line-length = 80
